version: '3.8'

services:
  postgres:
    image: postgres:9.5
    container_name: postgres_loja_virtual
    environment:
      POSTGRES_DB: loja_virtual_mentoria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
